services:
  extractor:
    build: ./extractor
    container_name: extractor-container
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity


  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container
    ports:
      - "11434:11434"
    # environment:
    #   - OLLAMA_HOST=0.0.0.0
    # restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  
  db:
    image: postgres
    container_name: db-container
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB


  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 80:80
    container_name: pgadmin4-container
    volumes:
      # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
      - pgadmin_storage:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD


volumes:
  pgadmin_storage:
