services:
  extractor:
    volumes:
      # Mount the root folder that contains .git
      # - .:/workspace
      - ./extractor:/workspace/extractor
      - ./src:/workspace/extractor/src
    command: sleep infinity
    depends_on: !reset []
    ports:
      - "8000:8000"

    